version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    # build: .
    image: wurstmeister/kafka:2.13-2.6.0
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.10 # ifconfig en0
      RACK_COMMAND: hostname
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_REPLICA_SELECTOR_CLASS: org.apache.kafka.common.replica.RackAwareReplicaSelector
      KAFKA_CREATE_TOPICS: test-1:1:2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
